package com.example.eksamensprojekt2022.PostCode;

import org.json.JSONArray;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;


public class PostNumberToCity {


    public static HashMap<Integer, String> postalToCityMap = new HashMap<Integer, String>(


    );

    // Adding Key and Value pairs to HashMap


    public static String getCityFromPostCode(int postCode) {

        return postalToCityMap.get(postCode);



    }

    public static void createPostCodeHasMap()  {


        postalToCityMap.put(1001,"København K");
        postalToCityMap.put(1002,"København K");
        postalToCityMap.put(1003,"København K");
        postalToCityMap.put(1004,"København K");
        postalToCityMap.put(1005,"København K");
        postalToCityMap.put(1006,"København K");
        postalToCityMap.put(1007,"København K");
        postalToCityMap.put(1008,"København K");
        postalToCityMap.put(1009,"København K");
        postalToCityMap.put(1010,"København K");
        postalToCityMap.put(1011,"København K");
        postalToCityMap.put(1012,"København K");
        postalToCityMap.put(1013,"København K");
        postalToCityMap.put(1014,"København K");
        postalToCityMap.put(1015,"København K");
        postalToCityMap.put(1016,"København K");
        postalToCityMap.put(1017,"København K");
        postalToCityMap.put(1018,"København K");
        postalToCityMap.put(1019,"København K");
        postalToCityMap.put(1020,"København K");
        postalToCityMap.put(1021,"København K");
        postalToCityMap.put(1022,"København K");
        postalToCityMap.put(1023,"København K");
        postalToCityMap.put(1024,"København K");
        postalToCityMap.put(1025,"København K");
        postalToCityMap.put(1026,"København K");
        postalToCityMap.put(1045,"København K");
        postalToCityMap.put(1050,"København K");
        postalToCityMap.put(1051,"København K");
        postalToCityMap.put(1052,"København K");
        postalToCityMap.put(1053,"København K");
        postalToCityMap.put(1054,"København K");
        postalToCityMap.put(1055,"København K");
        postalToCityMap.put(1055,"København K");
        postalToCityMap.put(1056,"København K");
        postalToCityMap.put(1057,"København K");
        postalToCityMap.put(1058,"København K");
        postalToCityMap.put(1059,"København K");
        postalToCityMap.put(1060,"København K");
        postalToCityMap.put(1061,"København K");
        postalToCityMap.put(1062,"København K");
        postalToCityMap.put(1063,"København K");
        postalToCityMap.put(1064,"København K");
        postalToCityMap.put(1065,"København K");
        postalToCityMap.put(1066,"København K");
        postalToCityMap.put(1067,"København K");
        postalToCityMap.put(1068,"København K");
        postalToCityMap.put(1069,"København K");
        postalToCityMap.put(1070,"København K");
        postalToCityMap.put(1071,"København K");
        postalToCityMap.put(1072,"København K");
        postalToCityMap.put(1073,"København K");
        postalToCityMap.put(1074,"København K");
        postalToCityMap.put(1092,"København K");
        postalToCityMap.put(1093,"København K");
        postalToCityMap.put(1095,"København K");
        postalToCityMap.put(1098,"København K");
        postalToCityMap.put(1100,"København K");
        postalToCityMap.put(1101,"København K");
        postalToCityMap.put(1102,"København K");
        postalToCityMap.put(1103,"København K");
        postalToCityMap.put(1104,"København K");
        postalToCityMap.put(1105,"København K");
        postalToCityMap.put(1106,"København K");
        postalToCityMap.put(1107,"København K");
        postalToCityMap.put(1110,"København K");
        postalToCityMap.put(1111,"København K");
        postalToCityMap.put(1112,"København K");
        postalToCityMap.put(1113,"København K");
        postalToCityMap.put(1114,"København K");
        postalToCityMap.put(1115,"København K");
        postalToCityMap.put(1116,"København K");
        postalToCityMap.put(1117,"København K");
        postalToCityMap.put(1118,"København K");
        postalToCityMap.put(1119,"København K");
        postalToCityMap.put(1120,"København K");
        postalToCityMap.put(1121,"København K");
        postalToCityMap.put(1122,"København K");
        postalToCityMap.put(1123,"København K");
        postalToCityMap.put(1124,"København K");
        postalToCityMap.put(1125,"København K");
        postalToCityMap.put(1126,"København K");
        postalToCityMap.put(1127,"København K");
        postalToCityMap.put(1128,"København K");
        postalToCityMap.put(1129,"København K");
        postalToCityMap.put(1130,"København K");
        postalToCityMap.put(1131,"København K");
        postalToCityMap.put(1140,"København K");
        postalToCityMap.put(1147,"København K");
        postalToCityMap.put(1148,"København K");
        postalToCityMap.put(1150,"København K");
        postalToCityMap.put(1151,"København K");
        postalToCityMap.put(1152,"København K");
        postalToCityMap.put(1153,"København K");
        postalToCityMap.put(1154,"København K");
        postalToCityMap.put(1155,"København K");
        postalToCityMap.put(1156,"København K");
        postalToCityMap.put(1157,"København K");
        postalToCityMap.put(1158,"København K");
        postalToCityMap.put(1159,"København K");
        postalToCityMap.put(1160,"København K");
        postalToCityMap.put(1161,"København K");
        postalToCityMap.put(1162,"København K");
        postalToCityMap.put(1164,"København K");
        postalToCityMap.put(1165,"København K");
        postalToCityMap.put(1165,"København K");
        postalToCityMap.put(1166,"København K");
        postalToCityMap.put(1167,"København K");
        postalToCityMap.put(1168,"København K");
        postalToCityMap.put(1169,"København K");
        postalToCityMap.put(1170,"København K");
        postalToCityMap.put(1171,"København K");
        postalToCityMap.put(1172,"København K");
        postalToCityMap.put(1173,"København K");
        postalToCityMap.put(1174,"København K");
        postalToCityMap.put(1175,"København K");
        postalToCityMap.put(1200,"København K");
        postalToCityMap.put(1201,"København K");
        postalToCityMap.put(1202,"København K");
        postalToCityMap.put(1203,"København K");
        postalToCityMap.put(1204,"København K");
        postalToCityMap.put(1205,"København K");
        postalToCityMap.put(1206,"København K");
        postalToCityMap.put(1207,"København K");
        postalToCityMap.put(1208,"København K");
        postalToCityMap.put(1209,"København K");
        postalToCityMap.put(1210,"København K");
        postalToCityMap.put(1211,"København K");
        postalToCityMap.put(1212,"København K");
        postalToCityMap.put(1213,"København K");
        postalToCityMap.put(1214,"København K");
        postalToCityMap.put(1215,"København K");
        postalToCityMap.put(1216,"København K");
        postalToCityMap.put(1217,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1218,"København K");
        postalToCityMap.put(1219,"København K");
        postalToCityMap.put(1220,"København K");
        postalToCityMap.put(1221,"København K");
        postalToCityMap.put(1240,"København K");
        postalToCityMap.put(1250,"København K");
        postalToCityMap.put(1251,"København K");
        postalToCityMap.put(1252,"København K");
        postalToCityMap.put(1253,"København K");
        postalToCityMap.put(1254,"København K");
        postalToCityMap.put(1255,"København K");
        postalToCityMap.put(1256,"København K");
        postalToCityMap.put(1257,"København K");
        postalToCityMap.put(1259,"København K");
        postalToCityMap.put(1259,"København K");
        postalToCityMap.put(1260,"København K");
        postalToCityMap.put(1261,"København K");
        postalToCityMap.put(1263,"København K");
        postalToCityMap.put(1263,"København K");
        postalToCityMap.put(1264,"København K");
        postalToCityMap.put(1265,"København K");
        postalToCityMap.put(1266,"København K");
        postalToCityMap.put(1267,"København K");
        postalToCityMap.put(1268,"København K");
        postalToCityMap.put(1270,"København K");
        postalToCityMap.put(1271,"København K");
        postalToCityMap.put(1300,"København K");
        postalToCityMap.put(1301,"København K");
        postalToCityMap.put(1302,"København K");
        postalToCityMap.put(1303,"København K");
        postalToCityMap.put(1304,"København K");
        postalToCityMap.put(1306,"København K");
        postalToCityMap.put(1307,"København K");
        postalToCityMap.put(1307,"København K");
        postalToCityMap.put(1308,"København K");
        postalToCityMap.put(1309,"København K");
        postalToCityMap.put(1310,"København K");
        postalToCityMap.put(1311,"København K");
        postalToCityMap.put(1312,"København K");
        postalToCityMap.put(1313,"København K");
        postalToCityMap.put(1314,"København K");
        postalToCityMap.put(1315,"København K");
        postalToCityMap.put(1316,"København K");
        postalToCityMap.put(1317,"København K");
        postalToCityMap.put(1318,"København K");
        postalToCityMap.put(1319,"København K");
        postalToCityMap.put(1320,"København K");
        postalToCityMap.put(1321,"København K");
        postalToCityMap.put(1322,"København K");
        postalToCityMap.put(1323,"København K");
        postalToCityMap.put(1324,"København K");
        postalToCityMap.put(1325,"København K");
        postalToCityMap.put(1326,"København K");
        postalToCityMap.put(1327,"København K");
        postalToCityMap.put(1328,"København K");
        postalToCityMap.put(1329,"København K");
        postalToCityMap.put(1350,"København K");
        postalToCityMap.put(1352,"København K");
        postalToCityMap.put(1353,"København K");
        postalToCityMap.put(1354,"København K");
        postalToCityMap.put(1355,"København K");
        postalToCityMap.put(1356,"København K");
        postalToCityMap.put(1357,"København K");
        postalToCityMap.put(1358,"København K");
        postalToCityMap.put(1359,"København K");
        postalToCityMap.put(1359,"København K");
        postalToCityMap.put(1360,"København K");
        postalToCityMap.put(1361,"København K");
        postalToCityMap.put(1361,"København K");
        postalToCityMap.put(1362,"København K");
        postalToCityMap.put(1363,"København K");
        postalToCityMap.put(1364,"København K");
        postalToCityMap.put(1365,"København K");
        postalToCityMap.put(1366,"København K");
        postalToCityMap.put(1367,"København K");
        postalToCityMap.put(1368,"København K");
        postalToCityMap.put(1369,"København K");
        postalToCityMap.put(1370,"København K");
        postalToCityMap.put(1371,"København K");
        postalToCityMap.put(1400,"København K");
        postalToCityMap.put(1400,"København K");
        postalToCityMap.put(1401,"København K");
        postalToCityMap.put(1402,"København K");
        postalToCityMap.put(1402,"København K");
        postalToCityMap.put(1402,"København K");
        postalToCityMap.put(1402,"København K");
        postalToCityMap.put(1402,"København K");
        postalToCityMap.put(1403,"København K");
        postalToCityMap.put(1406,"København K");
        postalToCityMap.put(1407,"København K");
        postalToCityMap.put(1408,"København K");
        postalToCityMap.put(1409,"København K");
        postalToCityMap.put(1410,"København K");
        postalToCityMap.put(1411,"København K");
        postalToCityMap.put(1411,"København K");
        postalToCityMap.put(1412,"København K");
        postalToCityMap.put(1413,"København K");
        postalToCityMap.put(1414,"København K");
        postalToCityMap.put(1415,"København K");
        postalToCityMap.put(1416,"København K");
        postalToCityMap.put(1417,"København K");
        postalToCityMap.put(1418,"København K");
        postalToCityMap.put(1419,"København K");
        postalToCityMap.put(1420,"København K");
        postalToCityMap.put(1421,"København K");
        postalToCityMap.put(1422,"København K");
        postalToCityMap.put(1423,"København K");
        postalToCityMap.put(1424,"København K");
        postalToCityMap.put(1425,"København K");
        postalToCityMap.put(1426,"København K");
        postalToCityMap.put(1427,"København K");
        postalToCityMap.put(1428,"København K");
        postalToCityMap.put(1429,"København K");
        postalToCityMap.put(1430,"København K");
        postalToCityMap.put(1432,"København K");
        postalToCityMap.put(1432,"København K");
        postalToCityMap.put(1432,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1433,"København K");
        postalToCityMap.put(1434,"København K");
        postalToCityMap.put(1434,"København K");
        postalToCityMap.put(1435,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1436,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1437,"København K");
        postalToCityMap.put(1438,"København K");
        postalToCityMap.put(1438,"København K");
        postalToCityMap.put(1438,"København K");
        postalToCityMap.put(1438,"København K");
        postalToCityMap.put(1438,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1439,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1440,"København K");
        postalToCityMap.put(1441,"København K");
        postalToCityMap.put(1441,"København K");
        postalToCityMap.put(1441,"København K");
        postalToCityMap.put(1448,"København K");
        postalToCityMap.put(1450,"København K");
        postalToCityMap.put(1451,"København K");
        postalToCityMap.put(1452,"København K");
        postalToCityMap.put(1453,"København K");
        postalToCityMap.put(1454,"København K");
        postalToCityMap.put(1455,"København K");
        postalToCityMap.put(1456,"København K");
        postalToCityMap.put(1457,"København K");
        postalToCityMap.put(1458,"København K");
        postalToCityMap.put(1459,"København K");
        postalToCityMap.put(1460,"København K");
        postalToCityMap.put(1461,"København K");
        postalToCityMap.put(1462,"København K");
        postalToCityMap.put(1463,"København K");
        postalToCityMap.put(1464,"København K");
        postalToCityMap.put(1465,"København K");
        postalToCityMap.put(1466,"København K");
        postalToCityMap.put(1467,"København K");
        postalToCityMap.put(1468,"København K");
        postalToCityMap.put(1470,"København K");
        postalToCityMap.put(1471,"København K");
        postalToCityMap.put(1472,"København K");
        postalToCityMap.put(1473,"København K");
        postalToCityMap.put(1500,"København V");
        postalToCityMap.put(1501,"København V");
        postalToCityMap.put(1502,"København V");
        postalToCityMap.put(1503,"København V");
        postalToCityMap.put(1504,"København V");
        postalToCityMap.put(1505,"København V");
        postalToCityMap.put(1506,"København V");
        postalToCityMap.put(1507,"København V");
        postalToCityMap.put(1508,"København V");
        postalToCityMap.put(1509,"København V");
        postalToCityMap.put(1510,"København V");
        postalToCityMap.put(1512,"Returpost");
        postalToCityMap.put(1513,"Flytninger og Nejtak");
        postalToCityMap.put(1532,"København V");
        postalToCityMap.put(1533,"København V");
        postalToCityMap.put(1550,"København V");
        postalToCityMap.put(1550,"København V");
        postalToCityMap.put(1551,"København V");
        postalToCityMap.put(1552,"København V");
        postalToCityMap.put(1553,"København V");
        postalToCityMap.put(1553,"København V");
        postalToCityMap.put(1554,"København V");
        postalToCityMap.put(1555,"København V");
        postalToCityMap.put(1556,"København V");
        postalToCityMap.put(1557,"København V");
        postalToCityMap.put(1558,"København V");
        postalToCityMap.put(1559,"København V");
        postalToCityMap.put(1560,"København V");
        postalToCityMap.put(1561,"København V");
        postalToCityMap.put(1561,"København V");
        postalToCityMap.put(1562,"København V");
        postalToCityMap.put(1563,"København V");
        postalToCityMap.put(1564,"København V");
        postalToCityMap.put(1567,"København V");
        postalToCityMap.put(1568,"København V");
        postalToCityMap.put(1569,"København V");
        postalToCityMap.put(1570,"København V");
        postalToCityMap.put(1570,"København V");
        postalToCityMap.put(1571,"København V");
        postalToCityMap.put(1572,"København V");
        postalToCityMap.put(1573,"København V");
        postalToCityMap.put(1574,"København V");
        postalToCityMap.put(1575,"København V");
        postalToCityMap.put(1576,"København V");
        postalToCityMap.put(1577,"København V");
        postalToCityMap.put(1577,"København V");
        postalToCityMap.put(1577,"København V");
        postalToCityMap.put(1592,"København V");
        postalToCityMap.put(1599,"København V");
        postalToCityMap.put(1600,"København V");
        postalToCityMap.put(1601,"København V");
        postalToCityMap.put(1602,"København V");
        postalToCityMap.put(1603,"København V");
        postalToCityMap.put(1604,"København V");
        postalToCityMap.put(1605,"København V");
        postalToCityMap.put(1606,"København V");
        postalToCityMap.put(1607,"København V");
        postalToCityMap.put(1608,"København V");
        postalToCityMap.put(1609,"København V");
        postalToCityMap.put(1610,"København V");
        postalToCityMap.put(1611,"København V");
        postalToCityMap.put(1612,"København V");
        postalToCityMap.put(1613,"København V");
        postalToCityMap.put(1614,"København V");
        postalToCityMap.put(1615,"København V");
        postalToCityMap.put(1616,"København V");
        postalToCityMap.put(1617,"København V");
        postalToCityMap.put(1618,"København V");
        postalToCityMap.put(1619,"København V");
        postalToCityMap.put(1620,"København V");
        postalToCityMap.put(1620,"København V");
        postalToCityMap.put(1621,"København V");
        postalToCityMap.put(1622,"København V");
        postalToCityMap.put(1623,"København V");
        postalToCityMap.put(1624,"København V");
        postalToCityMap.put(1630,"København V");
        postalToCityMap.put(1631,"København V");
        postalToCityMap.put(1632,"København V");
        postalToCityMap.put(1633,"København V");
        postalToCityMap.put(1634,"København V");
        postalToCityMap.put(1635,"København V");
        postalToCityMap.put(1650,"København V");
        postalToCityMap.put(1651,"København V");
        postalToCityMap.put(1652,"København V");
        postalToCityMap.put(1653,"København V");
        postalToCityMap.put(1654,"København V");
        postalToCityMap.put(1655,"København V");
        postalToCityMap.put(1656,"København V");
        postalToCityMap.put(1657,"København V");
        postalToCityMap.put(1658,"København V");
        postalToCityMap.put(1659,"København V");
        postalToCityMap.put(1660,"København V");
        postalToCityMap.put(1660,"København V");
        postalToCityMap.put(1661,"København V");
        postalToCityMap.put(1662,"København V");
        postalToCityMap.put(1663,"København V");
        postalToCityMap.put(1664,"København V");
        postalToCityMap.put(1665,"København V");
        postalToCityMap.put(1666,"København V");
        postalToCityMap.put(1667,"København V");
        postalToCityMap.put(1668,"København V");
        postalToCityMap.put(1669,"København V");
        postalToCityMap.put(1670,"København V");
        postalToCityMap.put(1671,"København V");
        postalToCityMap.put(1671,"København V");
        postalToCityMap.put(1672,"København V");
        postalToCityMap.put(1673,"København V");
        postalToCityMap.put(1674,"København V");
        postalToCityMap.put(1675,"København V");
        postalToCityMap.put(1676,"København V");
        postalToCityMap.put(1677,"København V");
        postalToCityMap.put(1699,"København V");
        postalToCityMap.put(1700,"København V");
        postalToCityMap.put(1701,"København V");
        postalToCityMap.put(1702,"København V");
        postalToCityMap.put(1703,"København V");
        postalToCityMap.put(1704,"København V");
        postalToCityMap.put(1705,"København V");
        postalToCityMap.put(1706,"København V");
        postalToCityMap.put(1707,"København V");
        postalToCityMap.put(1708,"København V");
        postalToCityMap.put(1709,"København V");
        postalToCityMap.put(1710,"København V");
        postalToCityMap.put(1711,"København V");
        postalToCityMap.put(1711,"København V");
        postalToCityMap.put(1712,"København V");
        postalToCityMap.put(1714,"København V");
        postalToCityMap.put(1715,"København V");
        postalToCityMap.put(1716,"København V");
        postalToCityMap.put(1717,"København V");
        postalToCityMap.put(1718,"København V");
        postalToCityMap.put(1719,"København V");
        postalToCityMap.put(1720,"København V");
        postalToCityMap.put(1721,"København V");
        postalToCityMap.put(1722,"København V");
        postalToCityMap.put(1723,"København V");
        postalToCityMap.put(1724,"København V");
        postalToCityMap.put(1725,"København V");
        postalToCityMap.put(1726,"København V");
        postalToCityMap.put(1727,"København V");
        postalToCityMap.put(1728,"København V");
        postalToCityMap.put(1729,"København V");
        postalToCityMap.put(1730,"København V");
        postalToCityMap.put(1731,"København V");
        postalToCityMap.put(1732,"København V");
        postalToCityMap.put(1733,"København V");
        postalToCityMap.put(1734,"København V");
        postalToCityMap.put(1735,"København V");
        postalToCityMap.put(1736,"København V");
        postalToCityMap.put(1737,"København V");
        postalToCityMap.put(1738,"København V");
        postalToCityMap.put(1739,"København V");
        postalToCityMap.put(1749,"København V");
        postalToCityMap.put(1750,"København V");
        postalToCityMap.put(1751,"København V");
        postalToCityMap.put(1752,"København V");
        postalToCityMap.put(1753,"København V");
        postalToCityMap.put(1754,"København V");
        postalToCityMap.put(1755,"København V");
        postalToCityMap.put(1756,"København V");
        postalToCityMap.put(1757,"København V");
        postalToCityMap.put(1758,"København V");
        postalToCityMap.put(1759,"København V");
        postalToCityMap.put(1760,"København V");
        postalToCityMap.put(1761,"København V");
        postalToCityMap.put(1762,"København V");
        postalToCityMap.put(1763,"København V");
        postalToCityMap.put(1764,"København V");
        postalToCityMap.put(1765,"København V");
        postalToCityMap.put(1766,"København V");
        postalToCityMap.put(1770,"København V");
        postalToCityMap.put(1771,"København V");
        postalToCityMap.put(1772,"København V");
        postalToCityMap.put(1773,"København V");
        postalToCityMap.put(1774,"København V");
        postalToCityMap.put(1775,"København V");
        postalToCityMap.put(1777,"København V");
        postalToCityMap.put(1780,"København V");
        postalToCityMap.put(1782,"København V");
        postalToCityMap.put(1785,"København V");
        postalToCityMap.put(1786,"København V");
        postalToCityMap.put(1787,"København V");
        postalToCityMap.put(1790,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1799,"København V");
        postalToCityMap.put(1800,"Frederiksberg C");
        postalToCityMap.put(1801,"Frederiksberg C");
        postalToCityMap.put(1802,"Frederiksberg C");
        postalToCityMap.put(1803,"Frederiksberg C");
        postalToCityMap.put(1804,"Frederiksberg C");
        postalToCityMap.put(1805,"Frederiksberg C");
        postalToCityMap.put(1806,"Frederiksberg C");
        postalToCityMap.put(1807,"Frederiksberg C");
        postalToCityMap.put(1808,"Frederiksberg C");
        postalToCityMap.put(1809,"Frederiksberg C");
        postalToCityMap.put(1810,"Frederiksberg C");
        postalToCityMap.put(1811,"Frederiksberg C");
        postalToCityMap.put(1812,"Frederiksberg C");
        postalToCityMap.put(1813,"Frederiksberg C");
        postalToCityMap.put(1814,"Frederiksberg C");
        postalToCityMap.put(1815,"Frederiksberg C");
        postalToCityMap.put(1816,"Frederiksberg C");
        postalToCityMap.put(1817,"Frederiksberg C");
        postalToCityMap.put(1818,"Frederiksberg C");
        postalToCityMap.put(1819,"Frederiksberg C");
        postalToCityMap.put(1820,"Frederiksberg C");
        postalToCityMap.put(1822,"Frederiksberg C");
        postalToCityMap.put(1823,"Frederiksberg C");
        postalToCityMap.put(1824,"Frederiksberg C");
        postalToCityMap.put(1825,"Frederiksberg C");
        postalToCityMap.put(1826,"Frederiksberg C");
        postalToCityMap.put(1827,"Frederiksberg C");
        postalToCityMap.put(1828,"Frederiksberg C");
        postalToCityMap.put(1829,"Frederiksberg C");
        postalToCityMap.put(1835,"Frederiksberg C");
        postalToCityMap.put(1850,"Frederiksberg C");
        postalToCityMap.put(1851,"Frederiksberg C");
        postalToCityMap.put(1852,"Frederiksberg C");
        postalToCityMap.put(1853,"Frederiksberg C");
        postalToCityMap.put(1854,"Frederiksberg C");
        postalToCityMap.put(1855,"Frederiksberg C");
        postalToCityMap.put(1856,"Frederiksberg C");
        postalToCityMap.put(1857,"Frederiksberg C");
        postalToCityMap.put(1860,"Frederiksberg C");
        postalToCityMap.put(1861,"Frederiksberg C");
        postalToCityMap.put(1862,"Frederiksberg C");
        postalToCityMap.put(1863,"Frederiksberg C");
        postalToCityMap.put(1864,"Frederiksberg C");
        postalToCityMap.put(1865,"Frederiksberg C");
        postalToCityMap.put(1866,"Frederiksberg C");
        postalToCityMap.put(1867,"Frederiksberg C");
        postalToCityMap.put(1868,"Frederiksberg C");
        postalToCityMap.put(1870,"Frederiksberg C");
        postalToCityMap.put(1871,"Frederiksberg C");
        postalToCityMap.put(1872,"Frederiksberg C");
        postalToCityMap.put(1873,"Frederiksberg C");
        postalToCityMap.put(1874,"Frederiksberg C");
        postalToCityMap.put(1875,"Frederiksberg C");
        postalToCityMap.put(1876,"Frederiksberg C");
        postalToCityMap.put(1877,"Frederiksberg C");
        postalToCityMap.put(1878,"Frederiksberg C");
        postalToCityMap.put(1879,"Frederiksberg C");
        postalToCityMap.put(1900,"Frederiksberg C");
        postalToCityMap.put(1901,"Frederiksberg C");
        postalToCityMap.put(1902,"Frederiksberg C");
        postalToCityMap.put(1903,"Frederiksberg C");
        postalToCityMap.put(1904,"Frederiksberg C");
        postalToCityMap.put(1905,"Frederiksberg C");
        postalToCityMap.put(1906,"Frederiksberg C");
        postalToCityMap.put(1908,"Frederiksberg C");
        postalToCityMap.put(1909,"Frederiksberg C");
        postalToCityMap.put(1910,"Frederiksberg C");
        postalToCityMap.put(1911,"Frederiksberg C");
        postalToCityMap.put(1912,"Frederiksberg C");
        postalToCityMap.put(1913,"Frederiksberg C");
        postalToCityMap.put(1914,"Frederiksberg C");
        postalToCityMap.put(1915,"Frederiksberg C");
        postalToCityMap.put(1916,"Frederiksberg C");
        postalToCityMap.put(1917,"Frederiksberg C");
        postalToCityMap.put(1920,"Frederiksberg C");
        postalToCityMap.put(1921,"Frederiksberg C");
        postalToCityMap.put(1922,"Frederiksberg C");
        postalToCityMap.put(1923,"Frederiksberg C");
        postalToCityMap.put(1924,"Frederiksberg C");
        postalToCityMap.put(1925,"Frederiksberg C");
        postalToCityMap.put(1926,"Frederiksberg C");
        postalToCityMap.put(1927,"Frederiksberg C");
        postalToCityMap.put(1928,"Frederiksberg C");
        postalToCityMap.put(1931,"Frederiksberg C");
        postalToCityMap.put(1950,"Frederiksberg C");
        postalToCityMap.put(1951,"Frederiksberg C");
        postalToCityMap.put(1952,"Frederiksberg C");
        postalToCityMap.put(1953,"Frederiksberg C");
        postalToCityMap.put(1954,"Frederiksberg C");
        postalToCityMap.put(1955,"Frederiksberg C");
        postalToCityMap.put(1956,"Frederiksberg C");
        postalToCityMap.put(1957,"Frederiksberg C");
        postalToCityMap.put(1958,"Frederiksberg C");
        postalToCityMap.put(1959,"Frederiksberg C");
        postalToCityMap.put(1960,"Frederiksberg C");
        postalToCityMap.put(1961,"Frederiksberg C");
        postalToCityMap.put(1962,"Frederiksberg C");
        postalToCityMap.put(1963,"Frederiksberg C");
        postalToCityMap.put(1964,"Frederiksberg C");
        postalToCityMap.put(1965,"Frederiksberg C");
        postalToCityMap.put(1966,"Frederiksberg C");
        postalToCityMap.put(1967,"Frederiksberg C");
        postalToCityMap.put(1970,"Frederiksberg C");
        postalToCityMap.put(1971,"Frederiksberg C");
        postalToCityMap.put(1972,"Frederiksberg C");
        postalToCityMap.put(1973,"Frederiksberg C");
        postalToCityMap.put(1974,"Frederiksberg C");
        postalToCityMap.put(2000,"Frederiksberg");
        postalToCityMap.put(2100,"København Ø");
        postalToCityMap.put(2150,"Nordhavn");
        postalToCityMap.put(2200,"København N");
        postalToCityMap.put(2300,"København S");
        postalToCityMap.put(2400,"København NV");
        postalToCityMap.put(2412,"Grønland");
        postalToCityMap.put(2412,"Santa Claus/Julemanden");
        postalToCityMap.put(2450,"København SV");
        postalToCityMap.put(2500,"Valby");
        postalToCityMap.put(2600,"Glostrup");
        postalToCityMap.put(2605,"Brøndby");
        postalToCityMap.put(2610,"Rødovre");
        postalToCityMap.put(2620,"Albertslund");
        postalToCityMap.put(2625,"Vallensbæk");
        postalToCityMap.put(2630,"Taastrup");
        postalToCityMap.put(2635,"Ishøj");
        postalToCityMap.put(2640,"Hedehusene");
        postalToCityMap.put(2644,"Spejdernes Lejr 2022");
        postalToCityMap.put(2650,"Hvidovre");
        postalToCityMap.put(2660,"Brøndby Strand");
        postalToCityMap.put(2665,"Vallensbæk Strand");
        postalToCityMap.put(2670,"Greve");
        postalToCityMap.put(2680,"Solrød Strand");
        postalToCityMap.put(2690,"Karlslunde");
        postalToCityMap.put(2700,"Brønshøj");
        postalToCityMap.put(2720,"Vanløse");
        postalToCityMap.put(2730,"Herlev");
        postalToCityMap.put(2740,"Skovlunde");
        postalToCityMap.put(2750,"Ballerup");
        postalToCityMap.put(2760,"Måløv");
        postalToCityMap.put(2765,"Smørum");
        postalToCityMap.put(2770,"Kastrup");
        postalToCityMap.put(2791,"Dragør");
        postalToCityMap.put(2800,"Kongens Lyngby");
        postalToCityMap.put(2820,"Gentofte");
        postalToCityMap.put(2830,"Virum");
        postalToCityMap.put(2840,"Holte");
        postalToCityMap.put(2850,"Nærum");
        postalToCityMap.put(2860,"Søborg");
        postalToCityMap.put(2870,"Dyssegård");
        postalToCityMap.put(2880,"Bagsværd");
        postalToCityMap.put(2900,"Hellerup");
        postalToCityMap.put(2920,"Charlottenlund");
        postalToCityMap.put(2930,"Klampenborg");
        postalToCityMap.put(2942,"Skodsborg");
        postalToCityMap.put(2950,"Vedbæk");
        postalToCityMap.put(2960,"Rungsted Kyst");
        postalToCityMap.put(2970,"Hørsholm");
        postalToCityMap.put(2980,"Kokkedal");
        postalToCityMap.put(2990,"Nivå");
        postalToCityMap.put(3000,"Helsingør");
        postalToCityMap.put(3050,"Humlebæk");
        postalToCityMap.put(3060,"Espergærde");
        postalToCityMap.put(3070,"Snekkersten");
        postalToCityMap.put(3080,"Tikøb");
        postalToCityMap.put(3100,"Hornbæk");
        postalToCityMap.put(3120,"Dronningmølle");
        postalToCityMap.put(3140,"Ålsgårde");
        postalToCityMap.put(3150,"Hellebæk");
        postalToCityMap.put(3200,"Helsinge");
        postalToCityMap.put(3210,"Vejby");
        postalToCityMap.put(3220,"Tisvildeleje");
        postalToCityMap.put(3230,"Græsted");
        postalToCityMap.put(3250,"Gilleleje");
        postalToCityMap.put(3300,"Frederiksværk");
        postalToCityMap.put(3310,"Ølsted");
        postalToCityMap.put(3320,"Skævinge");
        postalToCityMap.put(3330,"Gørløse");
        postalToCityMap.put(3360,"Liseleje");
        postalToCityMap.put(3370,"Melby");
        postalToCityMap.put(3390,"Hundested");
        postalToCityMap.put(3400,"Hillerød");
        postalToCityMap.put(3450,"Allerød");
        postalToCityMap.put(3460,"Birkerød");
        postalToCityMap.put(3480,"Fredensborg");
        postalToCityMap.put(3490,"Kvistgård");
        postalToCityMap.put(3500,"Værløse");
        postalToCityMap.put(3520,"Farum");
        postalToCityMap.put(3540,"Lynge");
        postalToCityMap.put(3550,"Slangerup");
        postalToCityMap.put(3600,"Frederikssund");
        postalToCityMap.put(3630,"Jægerspris");
        postalToCityMap.put(3650,"Ølstykke");
        postalToCityMap.put(3660,"Stenløse");
        postalToCityMap.put(3670,"Veksø Sjælland");
        postalToCityMap.put(3700,"Rønne");
        postalToCityMap.put(3720,"Aakirkeby");
        postalToCityMap.put(3730,"Nexø");
        postalToCityMap.put(3740,"Svaneke");
        postalToCityMap.put(3751,"Østermarie");
        postalToCityMap.put(3760,"Gudhjem");
        postalToCityMap.put(3770,"Allinge");
        postalToCityMap.put(3782,"Klemensker");
        postalToCityMap.put(3790,"Hasle");
        postalToCityMap.put(3900,"Nuuk");
        postalToCityMap.put(3905,"Nuussuaq");
        postalToCityMap.put(3910,"Kangerlussuaq");
        postalToCityMap.put(3911,"Sisimiut");
        postalToCityMap.put(3912,"Maniitsoq");
        postalToCityMap.put(3913,"Tasiilaq");
        postalToCityMap.put(3915,"Kulusuk");
        postalToCityMap.put(3919,"Alluitsup Paa");
        postalToCityMap.put(3920,"Qaqortoq");
        postalToCityMap.put(3921,"Narsaq");
        postalToCityMap.put(3922,"Nanortalik");
        postalToCityMap.put(3923,"Narsarsuaq");
        postalToCityMap.put(3924,"Ikerasassuaq");
        postalToCityMap.put(3930,"Kangilinnguit");
        postalToCityMap.put(3932,"Arsuk");
        postalToCityMap.put(3940,"Paamiut");
        postalToCityMap.put(3950,"Aasiaat");
        postalToCityMap.put(3951,"Qasigiannguit");
        postalToCityMap.put(3952,"Ilulissat");
        postalToCityMap.put(3953,"Qeqertarsuaq");
        postalToCityMap.put(3955,"Kangaatsiaq");
        postalToCityMap.put(3961,"Uummannaq");
        postalToCityMap.put(3962,"Upernavik");
        postalToCityMap.put(3964,"Qaarsut");
        postalToCityMap.put(3970,"Pituffik");
        postalToCityMap.put(3971,"Qaanaaq");
        postalToCityMap.put(3972,"Station Nord");
        postalToCityMap.put(3980,"Ittoqqortoormiit");
        postalToCityMap.put(3982,"Mestersvig");
        postalToCityMap.put(3984,"Danmarkshavn");
        postalToCityMap.put(3985,"Constable Pynt");
        postalToCityMap.put(3992,"Slædepatrulje Sirius");
        postalToCityMap.put(4000,"Roskilde");
        postalToCityMap.put(4030,"Tune");
        postalToCityMap.put(4040,"Jyllinge");
        postalToCityMap.put(4050,"Skibby");
        postalToCityMap.put(4060,"Kirke Såby");
        postalToCityMap.put(4070,"Kirke Hyllinge");
        postalToCityMap.put(4100,"Ringsted");
        postalToCityMap.put(4129,"Ringsted");
        postalToCityMap.put(4130,"Viby Sjælland");
        postalToCityMap.put(4140,"Borup");
        postalToCityMap.put(4160,"Herlufmagle");
        postalToCityMap.put(4171,"Glumsø");
        postalToCityMap.put(4173,"Fjenneslev");
        postalToCityMap.put(4174,"Jystrup Midtsj");
        postalToCityMap.put(4180,"Sorø");
        postalToCityMap.put(4190,"Munke Bjergby");
        postalToCityMap.put(4200,"Slagelse");
        postalToCityMap.put(4220,"Korsør");
        postalToCityMap.put(4230,"Skælskør");
        postalToCityMap.put(4241,"Vemmelev");
        postalToCityMap.put(4242,"Boeslunde");
        postalToCityMap.put(4243,"Rude");
        postalToCityMap.put(4244,"Agersø");
        postalToCityMap.put(4245,"Omø");
        postalToCityMap.put(4250,"Fuglebjerg");
        postalToCityMap.put(4261,"Dalmose");
        postalToCityMap.put(4262,"Sandved");
        postalToCityMap.put(4270,"Høng");
        postalToCityMap.put(4281,"Gørlev");
        postalToCityMap.put(4291,"Ruds Vedby");
        postalToCityMap.put(4293,"Dianalund");
        postalToCityMap.put(4295,"Stenlille");
        postalToCityMap.put(4296,"Nyrup");
        postalToCityMap.put(4300,"Holbæk");
        postalToCityMap.put(4305,"Orø");
        postalToCityMap.put(4320,"Lejre");
        postalToCityMap.put(4330,"Hvalsø");
        postalToCityMap.put(4340,"Tølløse");
        postalToCityMap.put(4350,"Ugerløse");
        postalToCityMap.put(4360,"Kirke Eskilstrup");
        postalToCityMap.put(4370,"Store Merløse");
        postalToCityMap.put(4390,"Vipperød");
        postalToCityMap.put(4400,"Kalundborg");
        postalToCityMap.put(4420,"Regstrup");
        postalToCityMap.put(4440,"Mørkøv");
        postalToCityMap.put(4450,"Jyderup");
        postalToCityMap.put(4460,"Snertinge");
        postalToCityMap.put(4470,"Svebølle");
        postalToCityMap.put(4480,"Store Fuglede");
        postalToCityMap.put(4490,"Jerslev Sjælland");
        postalToCityMap.put(4500,"Nykøbing Sj");
        postalToCityMap.put(4520,"Svinninge");
        postalToCityMap.put(4532,"Gislinge");
        postalToCityMap.put(4534,"Hørve");
        postalToCityMap.put(4540,"Fårevejle");
        postalToCityMap.put(4550,"Asnæs");
        postalToCityMap.put(4560,"Vig");
        postalToCityMap.put(4571,"Grevinge");
        postalToCityMap.put(4572,"Nørre Asmindrup");
        postalToCityMap.put(4573,"Højby");
        postalToCityMap.put(4581,"Rørvig");
        postalToCityMap.put(4583,"Sjællands Odde");
        postalToCityMap.put(4591,"Føllenslev");
        postalToCityMap.put(4592,"Sejerø");
        postalToCityMap.put(4593,"Eskebjerg");
        postalToCityMap.put(4600,"Køge");
        postalToCityMap.put(4621,"Gadstrup");
        postalToCityMap.put(4622,"Havdrup");
        postalToCityMap.put(4623,"Lille Skensved");
        postalToCityMap.put(4632,"Bjæverskov");
        postalToCityMap.put(4640,"Faxe");
        postalToCityMap.put(4652,"Hårlev");
        postalToCityMap.put(4653,"Karise");
        postalToCityMap.put(4654,"Faxe Ladeplads");
        postalToCityMap.put(4660,"Store Heddinge");
        postalToCityMap.put(4671,"Strøby");
        postalToCityMap.put(4672,"Klippinge");
        postalToCityMap.put(4673,"Rødvig Stevns");
        postalToCityMap.put(4681,"Herfølge");
        postalToCityMap.put(4682,"Tureby");
        postalToCityMap.put(4683,"Rønnede");
        postalToCityMap.put(4684,"Holmegaard");
        postalToCityMap.put(4690,"Haslev");
        postalToCityMap.put(4700,"Næstved");
        postalToCityMap.put(4720,"Præstø");
        postalToCityMap.put(4733,"Tappernøje");
        postalToCityMap.put(4735,"Mern");
        postalToCityMap.put(4736,"Karrebæksminde");
        postalToCityMap.put(4750,"Lundby");
        postalToCityMap.put(4760,"Vordingborg");
        postalToCityMap.put(4771,"Kalvehave");
        postalToCityMap.put(4772,"Langebæk");
        postalToCityMap.put(4773,"Stensved");
        postalToCityMap.put(4780,"Stege");
        postalToCityMap.put(4791,"Borre");
        postalToCityMap.put(4792,"Askeby");
        postalToCityMap.put(4793,"Bogø By");
        postalToCityMap.put(4800,"Nykøbing F");
        postalToCityMap.put(4840,"Nørre Alslev");
        postalToCityMap.put(4850,"Stubbekøbing");
        postalToCityMap.put(4862,"Guldborg");
        postalToCityMap.put(4863,"Eskilstrup");
        postalToCityMap.put(4871,"Horbelev");
        postalToCityMap.put(4872,"Idestrup");
        postalToCityMap.put(4873,"Væggerløse");
        postalToCityMap.put(4874,"Gedser");
        postalToCityMap.put(4880,"Nysted");
        postalToCityMap.put(4891,"Toreby L");
        postalToCityMap.put(4892,"Kettinge");
        postalToCityMap.put(4894,"Øster Ulslev");
        postalToCityMap.put(4895,"Errindlev");
        postalToCityMap.put(4900,"Nakskov");
        postalToCityMap.put(4912,"Harpelunde");
        postalToCityMap.put(4913,"Horslunde");
        postalToCityMap.put(4920,"Søllested");
        postalToCityMap.put(4930,"Maribo");
        postalToCityMap.put(4941,"Bandholm");
        postalToCityMap.put(4942,"Askø og Lilleø");
        postalToCityMap.put(4943,"Torrig L");
        postalToCityMap.put(4944,"Fejø");
        postalToCityMap.put(4945,"Femø");
        postalToCityMap.put(4951,"Nørreballe");
        postalToCityMap.put(4952,"Stokkemarke");
        postalToCityMap.put(4953,"Vesterborg");
        postalToCityMap.put(4960,"Holeby");
        postalToCityMap.put(4970,"Rødby");
        postalToCityMap.put(4983,"Dannemare");
        postalToCityMap.put(4990,"Sakskøbing");
        postalToCityMap.put(4992,"Midtsjælland USF P");
        postalToCityMap.put(5000,"Odense C");
        postalToCityMap.put(5029,"Odense C");
        postalToCityMap.put(5100,"Odense C");
        postalToCityMap.put(5200,"Odense V");
        postalToCityMap.put(5210,"Odense NV");
        postalToCityMap.put(5220,"Odense SØ");
        postalToCityMap.put(5230,"Odense M");
        postalToCityMap.put(5240,"Odense NØ");
        postalToCityMap.put(5250,"Odense SV");
        postalToCityMap.put(5260,"Odense S");
        postalToCityMap.put(5270,"Odense N");
        postalToCityMap.put(5290,"Marslev");
        postalToCityMap.put(5300,"Kerteminde");
        postalToCityMap.put(5320,"Agedrup");
        postalToCityMap.put(5330,"Munkebo");
        postalToCityMap.put(5350,"Rynkeby");
        postalToCityMap.put(5370,"Mesinge");
        postalToCityMap.put(5380,"Dalby");
        postalToCityMap.put(5390,"Martofte");
        postalToCityMap.put(5400,"Bogense");
        postalToCityMap.put(5450,"Otterup");
        postalToCityMap.put(5462,"Morud");
        postalToCityMap.put(5463,"Harndrup");
        postalToCityMap.put(5464,"Brenderup Fyn");
        postalToCityMap.put(5466,"Asperup");
        postalToCityMap.put(5471,"Søndersø");
        postalToCityMap.put(5474,"Veflinge");
        postalToCityMap.put(5485,"Skamby");
        postalToCityMap.put(5491,"Blommenslyst");
        postalToCityMap.put(5492,"Vissenbjerg");
        postalToCityMap.put(5500,"Middelfart");
        postalToCityMap.put(5540,"Ullerslev");
        postalToCityMap.put(5550,"Langeskov");
        postalToCityMap.put(5560,"Aarup");
        postalToCityMap.put(5580,"Nørre Aaby");
        postalToCityMap.put(5591,"Gelsted");
        postalToCityMap.put(5592,"Ejby");
        postalToCityMap.put(5600,"Faaborg");
        postalToCityMap.put(5601,"Lyø");
        postalToCityMap.put(5602,"Avernakø");
        postalToCityMap.put(5603,"Bjørnø");
        postalToCityMap.put(5610,"Assens");
        postalToCityMap.put(5620,"Glamsbjerg");
        postalToCityMap.put(5631,"Ebberup");
        postalToCityMap.put(5642,"Millinge");
        postalToCityMap.put(5672,"Broby");
        postalToCityMap.put(5683,"Haarby");
        postalToCityMap.put(5690,"Tommerup");
        postalToCityMap.put(5700,"Svendborg");
        postalToCityMap.put(5750,"Ringe");
        postalToCityMap.put(5762,"Vester Skerninge");
        postalToCityMap.put(5771,"Stenstrup");
        postalToCityMap.put(5772,"Kværndrup");
        postalToCityMap.put(5792,"Årslev");
        postalToCityMap.put(5800,"Nyborg");
        postalToCityMap.put(5853,"Ørbæk");
        postalToCityMap.put(5854,"Gislev");
        postalToCityMap.put(5856,"Ryslinge");
        postalToCityMap.put(5863,"Ferritslev Fyn");
        postalToCityMap.put(5871,"Frørup");
        postalToCityMap.put(5874,"Hesselager");
        postalToCityMap.put(5881,"Skårup Fyn");
        postalToCityMap.put(5882,"Vejstrup");
        postalToCityMap.put(5883,"Oure");
        postalToCityMap.put(5884,"Gudme");
        postalToCityMap.put(5892,"Gudbjerg Sydfyn");
        postalToCityMap.put(5900,"Rudkøbing");
        postalToCityMap.put(5932,"Humble");
        postalToCityMap.put(5935,"Bagenkop");
        postalToCityMap.put(5943,"Strynø");
        postalToCityMap.put(5953,"Tranekær");
        postalToCityMap.put(5960,"Marstal");
        postalToCityMap.put(5965,"Birkholm");
        postalToCityMap.put(5970,"Ærøskøbing");
        postalToCityMap.put(5985,"Søby Ærø");
        postalToCityMap.put(6000,"Kolding");
        postalToCityMap.put(6040,"Egtved");
        postalToCityMap.put(6051,"Almind");
        postalToCityMap.put(6052,"Viuf");
        postalToCityMap.put(6064,"Jordrup");
        postalToCityMap.put(6070,"Christiansfeld");
        postalToCityMap.put(6091,"Bjert");
        postalToCityMap.put(6092,"Sønder Stenderup");
        postalToCityMap.put(6093,"Sjølund");
        postalToCityMap.put(6094,"Hejls");
        postalToCityMap.put(6100,"Haderslev");
        postalToCityMap.put(6200,"Aabenraa");
        postalToCityMap.put(6210,"Barsø");
        postalToCityMap.put(6230,"Rødekro");
        postalToCityMap.put(6240,"Løgumkloster");
        postalToCityMap.put(6261,"Bredebro");
        postalToCityMap.put(6270,"Tønder");
        postalToCityMap.put(6280,"Højer");
        postalToCityMap.put(6300,"Gråsten");
        postalToCityMap.put(6310,"Broager");
        postalToCityMap.put(6320,"Egernsund");
        postalToCityMap.put(6330,"Padborg");
        postalToCityMap.put(6340,"Kruså");
        postalToCityMap.put(6360,"Tinglev");
        postalToCityMap.put(6372,"Bylderup-Bov");
        postalToCityMap.put(6392,"Bolderslev");
        postalToCityMap.put(6400,"Sønderborg");
        postalToCityMap.put(6430,"Nordborg");
        postalToCityMap.put(6440,"Augustenborg");
        postalToCityMap.put(6470,"Sydals");
        postalToCityMap.put(6500,"Vojens");
        postalToCityMap.put(6510,"Gram");
        postalToCityMap.put(6520,"Toftlund");
        postalToCityMap.put(6534,"Agerskov");
        postalToCityMap.put(6535,"Branderup J");
        postalToCityMap.put(6541,"Bevtoft");
        postalToCityMap.put(6560,"Sommersted");
        postalToCityMap.put(6580,"Vamdrup");
        postalToCityMap.put(6600,"Vejen");
        postalToCityMap.put(6621,"Gesten");
        postalToCityMap.put(6622,"Bække");
        postalToCityMap.put(6623,"Vorbasse");
        postalToCityMap.put(6630,"Rødding");
        postalToCityMap.put(6640,"Lunderskov");
        postalToCityMap.put(6650,"Brørup");
        postalToCityMap.put(6660,"Lintrup");
        postalToCityMap.put(6670,"Holsted");
        postalToCityMap.put(6682,"Hovborg");
        postalToCityMap.put(6683,"Føvling");
        postalToCityMap.put(6690,"Gørding");
        postalToCityMap.put(6700,"Esbjerg");
        postalToCityMap.put(6701,"Esbjerg");
        postalToCityMap.put(6705,"Esbjerg Ø");
        postalToCityMap.put(6710,"Esbjerg V");
        postalToCityMap.put(6715,"Esbjerg N");
        postalToCityMap.put(6720,"Fanø");
        postalToCityMap.put(6731,"Tjæreborg");
        postalToCityMap.put(6740,"Bramming");
        postalToCityMap.put(6752,"Glejbjerg");
        postalToCityMap.put(6753,"Agerbæk");
        postalToCityMap.put(6760,"Ribe");
        postalToCityMap.put(6771,"Gredstedbro");
        postalToCityMap.put(6780,"Skærbæk");
        postalToCityMap.put(6792,"Rømø");
        postalToCityMap.put(6800,"Varde");
        postalToCityMap.put(6818,"Årre");
        postalToCityMap.put(6823,"Ansager");
        postalToCityMap.put(6830,"Nørre Nebel");
        postalToCityMap.put(6840,"Oksbøl");
        postalToCityMap.put(6851,"Janderup Vestj");
        postalToCityMap.put(6852,"Billum");
        postalToCityMap.put(6853,"Vejers Strand");
        postalToCityMap.put(6854,"Henne");
        postalToCityMap.put(6855,"Outrup");
        postalToCityMap.put(6857,"Blåvand");
        postalToCityMap.put(6862,"Tistrup");
        postalToCityMap.put(6870,"Ølgod");
        postalToCityMap.put(6880,"Tarm");
        postalToCityMap.put(6893,"Hemmet");
        postalToCityMap.put(6900,"Skjern");
        postalToCityMap.put(6920,"Videbæk");
        postalToCityMap.put(6933,"Kibæk");
        postalToCityMap.put(6940,"Lem St");
        postalToCityMap.put(6950,"Ringkøbing");
        postalToCityMap.put(6960,"Hvide Sande");
        postalToCityMap.put(6971,"Spjald");
        postalToCityMap.put(6973,"Ørnhøj");
        postalToCityMap.put(6980,"Tim");
        postalToCityMap.put(6990,"Ulfborg");
        postalToCityMap.put(7000,"Fredericia");
        postalToCityMap.put(7007,"Fredericia");
        postalToCityMap.put(7017,"Taulov Pakkecenter");
        postalToCityMap.put(7018,"Pakker TLP");
        postalToCityMap.put(7029,"Fredericia");
        postalToCityMap.put(7080,"Børkop");
        postalToCityMap.put(7100,"Vejle");
        postalToCityMap.put(7120,"Vejle Øst");
        postalToCityMap.put(7130,"Juelsminde");
        postalToCityMap.put(7140,"Stouby");
        postalToCityMap.put(7150,"Barrit");
        postalToCityMap.put(7160,"Tørring");
        postalToCityMap.put(7171,"Uldum");
        postalToCityMap.put(7173,"Vonge");
        postalToCityMap.put(7182,"Bredsten");
        postalToCityMap.put(7183,"Randbøl");
        postalToCityMap.put(7184,"Vandel");
        postalToCityMap.put(7190,"Billund");
        postalToCityMap.put(7200,"Grindsted");
        postalToCityMap.put(7250,"Hejnsvig");
        postalToCityMap.put(7260,"Sønder Omme");
        postalToCityMap.put(7270,"Stakroge");
        postalToCityMap.put(7280,"Sønder Felding");
        postalToCityMap.put(7300,"Jelling");
        postalToCityMap.put(7321,"Gadbjerg");
        postalToCityMap.put(7323,"Give");
        postalToCityMap.put(7330,"Brande");
        postalToCityMap.put(7361,"Ejstrupholm");
        postalToCityMap.put(7362,"Hampen");
        postalToCityMap.put(7400,"Herning");
        postalToCityMap.put(7429,"Herning");
        postalToCityMap.put(7430,"Ikast");
        postalToCityMap.put(7441,"Bording");
        postalToCityMap.put(7442,"Engesvang");
        postalToCityMap.put(7451,"Sunds");
        postalToCityMap.put(7470,"Karup J");
        postalToCityMap.put(7480,"Vildbjerg");
        postalToCityMap.put(7490,"Aulum");
        postalToCityMap.put(7500,"Holstebro");
        postalToCityMap.put(7540,"Haderup");
        postalToCityMap.put(7550,"Sørvad");
        postalToCityMap.put(7560,"Hjerm");
        postalToCityMap.put(7570,"Vemb");
        postalToCityMap.put(7600,"Struer");
        postalToCityMap.put(7620,"Lemvig");
        postalToCityMap.put(7650,"Bøvlingbjerg");
        postalToCityMap.put(7660,"Bækmarksbro");
        postalToCityMap.put(7673,"Harboøre");
        postalToCityMap.put(7680,"Thyborøn");
        postalToCityMap.put(7700,"Thisted");
        postalToCityMap.put(7730,"Hanstholm");
        postalToCityMap.put(7741,"Frøstrup");
        postalToCityMap.put(7742,"Vesløs");
        postalToCityMap.put(7752,"Snedsted");
        postalToCityMap.put(7755,"Bedsted Thy");
        postalToCityMap.put(7760,"Hurup Thy");
        postalToCityMap.put(7770,"Vestervig");
        postalToCityMap.put(7790,"Thyholm");
        postalToCityMap.put(7800,"Skive");
        postalToCityMap.put(7830,"Vinderup");
        postalToCityMap.put(7840,"Højslev");
        postalToCityMap.put(7850,"Stoholm Jyll");
        postalToCityMap.put(7860,"Spøttrup");
        postalToCityMap.put(7870,"Roslev");
        postalToCityMap.put(7884,"Fur");
        postalToCityMap.put(7900,"Nykøbing M");
        postalToCityMap.put(7950,"Erslev");
        postalToCityMap.put(7960,"Karby");
        postalToCityMap.put(7970,"Redsted M");
        postalToCityMap.put(7980,"Vils");
        postalToCityMap.put(7990,"Øster Assels");
        postalToCityMap.put(7992,"Sydjylland/Fyn USF P");
        postalToCityMap.put(7993,"Sydjylland/Fyn USF B");
        postalToCityMap.put(7996,"Fakturaservice");
        postalToCityMap.put(7997,"Fakturascanning");
        postalToCityMap.put(7998,"Statsservice");
        postalToCityMap.put(7999,"Kommunepost");
        postalToCityMap.put(8000,"Aarhus C");
        postalToCityMap.put(8100,"Aarhus C");
        postalToCityMap.put(8200,"Aarhus N");
        postalToCityMap.put(8210,"Aarhus V");
        postalToCityMap.put(8220,"Brabrand");
        postalToCityMap.put(8229,"Risskov Ø");
        postalToCityMap.put(8230,"Åbyhøj");
        postalToCityMap.put(8240,"Risskov");
        postalToCityMap.put(8245,"Risskov Ø");
        postalToCityMap.put(8250,"Egå");
        postalToCityMap.put(8260,"Viby J");
        postalToCityMap.put(8270,"Højbjerg");
        postalToCityMap.put(8300,"Odder");
        postalToCityMap.put(8305,"Samsø");
        postalToCityMap.put(8310,"Tranbjerg J");
        postalToCityMap.put(8320,"Mårslet");
        postalToCityMap.put(8330,"Beder");
        postalToCityMap.put(8340,"Malling");
        postalToCityMap.put(8350,"Hundslund");
        postalToCityMap.put(8355,"Solbjerg");
        postalToCityMap.put(8361,"Hasselager");
        postalToCityMap.put(8362,"Hørning");
        postalToCityMap.put(8370,"Hadsten");
        postalToCityMap.put(8380,"Trige");
        postalToCityMap.put(8381,"Tilst");
        postalToCityMap.put(8382,"Hinnerup");
        postalToCityMap.put(8400,"Ebeltoft");
        postalToCityMap.put(8410,"Rønde");
        postalToCityMap.put(8420,"Knebel");
        postalToCityMap.put(8444,"Balle");
        postalToCityMap.put(8450,"Hammel");
        postalToCityMap.put(8462,"Harlev J");
        postalToCityMap.put(8464,"Galten");
        postalToCityMap.put(8471,"Sabro");
        postalToCityMap.put(8472,"Sporup");
        postalToCityMap.put(8500,"Grenaa");
        postalToCityMap.put(8520,"Lystrup");
        postalToCityMap.put(8530,"Hjortshøj");
        postalToCityMap.put(8541,"Skødstrup");
        postalToCityMap.put(8543,"Hornslet");
        postalToCityMap.put(8544,"Mørke");
        postalToCityMap.put(8550,"Ryomgård");
        postalToCityMap.put(8560,"Kolind");
        postalToCityMap.put(8570,"Trustrup");
        postalToCityMap.put(8581,"Nimtofte");
        postalToCityMap.put(8585,"Glesborg");
        postalToCityMap.put(8586,"Ørum Djurs");
        postalToCityMap.put(8592,"Anholt");
        postalToCityMap.put(8600,"Silkeborg");
        postalToCityMap.put(8620,"Kjellerup");
        postalToCityMap.put(8632,"Lemming");
        postalToCityMap.put(8641,"Sorring");
        postalToCityMap.put(8643,"Ans By");
        postalToCityMap.put(8653,"Them");
        postalToCityMap.put(8654,"Bryrup");
        postalToCityMap.put(8660,"Skanderborg");
        postalToCityMap.put(8670,"Låsby");
        postalToCityMap.put(8680,"Ry");
        postalToCityMap.put(8700,"Horsens");
        postalToCityMap.put(8721,"Daugård");
        postalToCityMap.put(8722,"Hedensted");
        postalToCityMap.put(8723,"Løsning");
        postalToCityMap.put(8732,"Hovedgård");
        postalToCityMap.put(8740,"Brædstrup");
        postalToCityMap.put(8751,"Gedved");
        postalToCityMap.put(8752,"Østbirk");
        postalToCityMap.put(8762,"Flemming");
        postalToCityMap.put(8763,"Rask Mølle");
        postalToCityMap.put(8765,"Klovborg");
        postalToCityMap.put(8766,"Nørre Snede");
        postalToCityMap.put(8781,"Stenderup");
        postalToCityMap.put(8783,"Hornsyld");
        postalToCityMap.put(8789,"Endelave");
        postalToCityMap.put(8799,"Tunø");
        postalToCityMap.put(8800,"Viborg");
        postalToCityMap.put(8830,"Tjele");
        postalToCityMap.put(8831,"Løgstrup");
        postalToCityMap.put(8832,"Skals");
        postalToCityMap.put(8840,"Rødkærsbro");
        postalToCityMap.put(8850,"Bjerringbro");
        postalToCityMap.put(8860,"Ulstrup");
        postalToCityMap.put(8870,"Langå");
        postalToCityMap.put(8881,"Thorsø");
        postalToCityMap.put(8882,"Fårvang");
        postalToCityMap.put(8883,"Gjern");
        postalToCityMap.put(8900,"Randers C");
        postalToCityMap.put(8920,"Randers NV");
        postalToCityMap.put(8930,"Randers NØ");
        postalToCityMap.put(8940,"Randers SV");
        postalToCityMap.put(8950,"Ørsted");
        postalToCityMap.put(8960,"Randers SØ");
        postalToCityMap.put(8961,"Allingåbro");
        postalToCityMap.put(8963,"Auning");
        postalToCityMap.put(8970,"Havndal");
        postalToCityMap.put(8981,"Spentrup");
        postalToCityMap.put(8983,"Gjerlev J");
        postalToCityMap.put(8990,"Fårup");
        postalToCityMap.put(9000,"Aalborg");
        postalToCityMap.put(9029,"Aalborg");
        postalToCityMap.put(9100,"Aalborg");
        postalToCityMap.put(9200,"Aalborg SV");
        postalToCityMap.put(9210,"Aalborg SØ");
        postalToCityMap.put(9220,"Aalborg Øst");
        postalToCityMap.put(9230,"Svenstrup J");
        postalToCityMap.put(9240,"Nibe");
        postalToCityMap.put(9260,"Gistrup");
        postalToCityMap.put(9270,"Klarup");
        postalToCityMap.put(9280,"Storvorde");
        postalToCityMap.put(9293,"Kongerslev");
        postalToCityMap.put(9300,"Sæby");
        postalToCityMap.put(9310,"Vodskov");
        postalToCityMap.put(9320,"Hjallerup");
        postalToCityMap.put(9330,"Dronninglund");
        postalToCityMap.put(9340,"Asaa");
        postalToCityMap.put(9352,"Dybvad");
        postalToCityMap.put(9362,"Gandrup");
        postalToCityMap.put(9370,"Hals");
        postalToCityMap.put(9380,"Vestbjerg");
        postalToCityMap.put(9381,"Sulsted");
        postalToCityMap.put(9382,"Tylstrup");
        postalToCityMap.put(9400,"Nørresundby");
        postalToCityMap.put(9430,"Vadum");
        postalToCityMap.put(9440,"Aabybro");
        postalToCityMap.put(9460,"Brovst");
        postalToCityMap.put(9480,"Løkken");
        postalToCityMap.put(9490,"Pandrup");
        postalToCityMap.put(9492,"Blokhus");
        postalToCityMap.put(9493,"Saltum");
        postalToCityMap.put(9500,"Hobro");
        postalToCityMap.put(9510,"Arden");
        postalToCityMap.put(9520,"Skørping");
        postalToCityMap.put(9530,"Støvring");
        postalToCityMap.put(9541,"Suldrup");
        postalToCityMap.put(9550,"Mariager");
        postalToCityMap.put(9560,"Hadsund");
        postalToCityMap.put(9574,"Bælum");
        postalToCityMap.put(9575,"Terndrup");
        postalToCityMap.put(9600,"Aars");
        postalToCityMap.put(9610,"Nørager");
        postalToCityMap.put(9620,"Aalestrup");
        postalToCityMap.put(9631,"Gedsted");
        postalToCityMap.put(9632,"Møldrup");
        postalToCityMap.put(9640,"Farsø");
        postalToCityMap.put(9670,"Løgstør");
        postalToCityMap.put(9681,"Ranum");
        postalToCityMap.put(9690,"Fjerritslev");
        postalToCityMap.put(9700,"Brønderslev");
        postalToCityMap.put(9740,"Jerslev J");
        postalToCityMap.put(9750,"Østervrå");
        postalToCityMap.put(9760,"Vrå");
        postalToCityMap.put(9800,"Hjørring");
        postalToCityMap.put(9830,"Tårs");
        postalToCityMap.put(9850,"Hirtshals");
        postalToCityMap.put(9870,"Sindal");
        postalToCityMap.put(9881,"Bindslev");
        postalToCityMap.put(9900,"Frederikshavn");
        postalToCityMap.put(9940,"Læsø");
        postalToCityMap.put(9970,"Strandby");
        postalToCityMap.put(9981,"Jerup");
        postalToCityMap.put(9982,"Ålbæk");
        postalToCityMap.put(9990,"Skagen");
        postalToCityMap.put(9992,"Jylland USF P");
        postalToCityMap.put(9993,"Jylland USF B");
        postalToCityMap.put(9996,"Fakturaservice");
        postalToCityMap.put(9997,"Fakturascanning");
        postalToCityMap.put(9998,"Borgerservice");



    }





}


